### ISSUE TITLE
Create checklist for producing a good map

### ISSUE THREAD

**Issue by mpjashby** [mpjashby/crimemapping#101]
- [x] Correct type (e.g. KDE better than choropleth)
- [x] Title, preferably declarative
- [x] Legend
- [x] Data attribution
- [x] Author
- [x] Date
- [x] Scale bar
- [x] North arrow only if necessary (specify when necessary)

**Comment by mpjashby** [comment]
Implemented in the big-bang release for the first half of the 2025 module
