### ISSUE TITLE
Tutorial 2 pre-flight checklist 2023

### ISSUE THREAD

**Issue by mpjashby** [mpjashby/crimemapping#53]
- [x] Add walk-through videos
- [x] Add questions
- [x] Add further reading
- [x] Add concluding message with thumbs up emoji
- [x] Make sure tutorial (or section) starts with the final map that we'll create
- [x] Make sure tutorial finishes with a complete script
- [x] Reduce image sizes using `harmonise_image_sizes()`
- [x] Spell check
- [x] Add `css: ["css/tutorial_style.css", "css/2023.css"]`
- [x] Increment package version number
- [ ] Check all code in RStudio Server
- [ ] Update Moodle

**Comment by mpjashby** [comment]
#43 will be dealt with here
