### ISSUE TITLE
Pre-flight checklist: tutorial 1, 2024

### ISSUE THREAD

**Issue by mpjashby** [mpjashby/crimemapping#86]
- [x] Add walk-through videos
- [x] Add questions
- [x] Add further reading
- [x] Make sure tutorial (or section) starts with the final map that we'll create
- [x] Make sure tutorial finishes with a complete script
- [x] Replace `ifelse()` with `if_else()` (Ctrl+F)
- [x] Replace `st_read()` with `read_sf()` (Ctrl+F)
- [x] Add `progress = "none"` to `annotation_map_tile()` (Ctrl+F)
- [x] Reduce image sizes using `harmonise_image_sizes()`
- [x] Spell check
- [x] Add `css: ["css/tutorial_style.css", "css/2024.css"]`
- [x] Check tutorial is not included in `.Rbuildignore`
- [x] Increment package version number
- [x] Add description of update to `NEWS.md`
- [x] Check all code in RStudio Server
- [x] Update Moodle

**Comment by mpjashby** [comment]
This was completed but I have no idea what commit did it
